//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-beta001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Generated from C:\Users\91018\Desktop\zlua\zlua\Lua.g4 by ANTLR 4.6.5-beta001
// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419
namespace zlua.Gen
{
    using Antlr4.Runtime.Misc;
    using Antlr4.Runtime.Tree;
    using System.Diagnostics;
    using IToken = Antlr4.Runtime.IToken;
    using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;
    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-beta001")]
    [System.CLSCompliant(false)]
    //[DebuggerStepThroughAttribute]
    public partial class LuaBaseVisitor<Result> : AbstractParseTreeVisitor<Result>, ILuaVisitor<Result>
    {
        public virtual Result VisitEmptyStat([NotNull] LuaParser.EmptyStatContext context) { return VisitChildren(context); }
        public virtual Result VisitAssignStat([NotNull] LuaParser.AssignStatContext context) { return VisitChildren(context); }
        public virtual Result VisitFunctioncallStat([NotNull] LuaParser.FunctioncallStatContext context) { return VisitChildren(context); }
        public virtual Result VisitBreakStat([NotNull] LuaParser.BreakStatContext context) { return VisitChildren(context); }
        public virtual Result VisitDoendStat([NotNull] LuaParser.DoendStatContext context) { return VisitChildren(context); }
        public virtual Result VisitWhileStat([NotNull] LuaParser.WhileStatContext context) { return VisitChildren(context); }
        public virtual Result VisitRepeatStat([NotNull] LuaParser.RepeatStatContext context) { return VisitChildren(context); }
        public virtual Result VisitIfelseStat([NotNull] LuaParser.IfelseStatContext context) { return VisitChildren(context); }
        public virtual Result VisitForijkStat([NotNull] LuaParser.ForijkStatContext context) { return VisitChildren(context); }
        public virtual Result VisitForinStat([NotNull] LuaParser.ForinStatContext context) { return VisitChildren(context); }
        public virtual Result VisitFunctiondefStat([NotNull] LuaParser.FunctiondefStatContext context) { return VisitChildren(context); }
        public virtual Result VisitLocalfunctiondefStat([NotNull] LuaParser.LocalfunctiondefStatContext context) { return VisitChildren(context); }
        public virtual Result VisitLocalassignStat([NotNull] LuaParser.LocalassignStatContext context) { return VisitChildren(context); }
        public virtual Result VisitNilfalsetruevarargExp([NotNull] LuaParser.NilfalsetruevarargExpContext context) { return VisitChildren(context); }
        public virtual Result VisitNumberExp([NotNull] LuaParser.NumberExpContext context) { return VisitChildren(context); }
        public virtual Result VisitStringExp([NotNull] LuaParser.StringExpContext context) { return VisitChildren(context); }
        public virtual Result VisitFunctiondefExp([NotNull] LuaParser.FunctiondefExpContext context) { return VisitChildren(context); }
        public virtual Result VisitPrefixexpExp([NotNull] LuaParser.PrefixexpExpContext context) { return VisitChildren(context); }
        public virtual Result VisitTablectorExp([NotNull] LuaParser.TablectorExpContext context) { return VisitChildren(context); }
        public virtual Result VisitPowExp([NotNull] LuaParser.PowExpContext context) { return VisitChildren(context); }
        public virtual Result VisitUnmExp([NotNull] LuaParser.UnmExpContext context) { return VisitChildren(context); }
        public virtual Result VisitMuldivExp([NotNull] LuaParser.MuldivExpContext context) { return VisitChildren(context); }
        public virtual Result VisitAddsubExp([NotNull] LuaParser.AddsubExpContext context) { return VisitChildren(context); }
        public virtual Result VisitConcatExp([NotNull] LuaParser.ConcatExpContext context) { return VisitChildren(context); }
        public virtual Result VisitCmpExp([NotNull] LuaParser.CmpExpContext context) { return VisitChildren(context); }
        public virtual Result VisitAndExp([NotNull] LuaParser.AndExpContext context) { return VisitChildren(context); }
        public virtual Result VisitOrExp([NotNull] LuaParser.OrExpContext context) { return VisitChildren(context); }
        public virtual Result VisitNormalArgs([NotNull] LuaParser.NormalArgsContext context) { return VisitChildren(context); }
        public virtual Result VisitTablectorArgs([NotNull] LuaParser.TablectorArgsContext context) { return VisitChildren(context); }
        public virtual Result VisitStringArgs([NotNull] LuaParser.StringArgsContext context) { return VisitChildren(context); }
        public virtual Result VisitChunk([NotNull] LuaParser.ChunkContext context) { return VisitChildren(context); }
        public virtual Result VisitBlock([NotNull] LuaParser.BlockContext context) { return VisitChildren(context); }
        public virtual Result VisitRetstat([NotNull] LuaParser.RetstatContext context) { return VisitChildren(context); }
        public virtual Result VisitStat([NotNull] LuaParser.StatContext context) { return VisitChildren(context); }
        public virtual Result VisitElseifBlock([NotNull] LuaParser.ElseifBlockContext context) { return VisitChildren(context); }
        public virtual Result VisitElseBlock([NotNull] LuaParser.ElseBlockContext context) { return VisitChildren(context); }
        public virtual Result VisitFuncname([NotNull] LuaParser.FuncnameContext context) { return VisitChildren(context); }
        public virtual Result VisitVarlist([NotNull] LuaParser.VarlistContext context) { return VisitChildren(context); }
        public virtual Result VisitNamelist([NotNull] LuaParser.NamelistContext context) { return VisitChildren(context); }
        public virtual Result VisitExplist([NotNull] LuaParser.ExplistContext context) { return VisitChildren(context); }
        public virtual Result VisitDoc([NotNull] LuaParser.DocContext context) { return VisitChildren(context); }
        public virtual Result VisitExp([NotNull] LuaParser.ExpContext context) { return VisitChildren(context); }
        public virtual Result VisitPrefixexp([NotNull] LuaParser.PrefixexpContext context) { return VisitChildren(context); }
        public virtual Result VisitFunctioncall([NotNull] LuaParser.FunctioncallContext context) { return VisitChildren(context); }
        public virtual Result VisitVarOrExp([NotNull] LuaParser.VarOrExpContext context) { return VisitChildren(context); }
        public virtual Result VisitVar([NotNull] LuaParser.VarContext context) { return VisitChildren(context); }
        public virtual Result VisitVarSuffix([NotNull] LuaParser.VarSuffixContext context) { return VisitChildren(context); }
        public virtual Result VisitNameAndArgs([NotNull] LuaParser.NameAndArgsContext context) { return VisitChildren(context); }
        public virtual Result VisitArgs([NotNull] LuaParser.ArgsContext context) { return VisitChildren(context); }
        public virtual Result VisitFunctiondef([NotNull] LuaParser.FunctiondefContext context) { return VisitChildren(context); }
        public virtual Result VisitFuncbody([NotNull] LuaParser.FuncbodyContext context) { return VisitChildren(context); }
        public virtual Result VisitParlist([NotNull] LuaParser.ParlistContext context) { return VisitChildren(context); }
        public virtual Result VisitTableconstructor([NotNull] LuaParser.TableconstructorContext context) { return VisitChildren(context); }
        public virtual Result VisitFieldlist([NotNull] LuaParser.FieldlistContext context) { return VisitChildren(context); }
        public virtual Result VisitField([NotNull] LuaParser.FieldContext context) { return VisitChildren(context); }
        public virtual Result VisitFieldsep([NotNull] LuaParser.FieldsepContext context) { return VisitChildren(context); }
        public virtual Result VisitNumber([NotNull] LuaParser.NumberContext context) { return VisitChildren(context); }
        public virtual Result VisitString([NotNull] LuaParser.StringContext context) { return VisitChildren(context); }
    }
} // namespace zlua.Gen
