//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-beta001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\91018\Desktop\zlua\zlua\Lua.g4 by ANTLR 4.6.5-beta001

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace zlua.AntlrGen
{

    using Antlr4.Runtime.Misc;
    using System.Diagnostics;
    using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
    using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
    using IToken = Antlr4.Runtime.IToken;
    using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

    /// <summary>
    /// This class provides an empty implementation of <see cref="ILuaListener"/>,
    /// which can be extended to create a listener which only needs to handle a subset
    /// of the available methods.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-beta001")]
    [System.CLSCompliant(false)]
    public partial class LuaBaseListener : ILuaListener
    {
        /// <summary>
        /// Enter a parse tree produced by the <c>emptyStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterEmptyStat([NotNull] LuaParser.EmptyStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>emptyStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitEmptyStat([NotNull] LuaParser.EmptyStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>assignStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterAssignStat([NotNull] LuaParser.AssignStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>assignStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitAssignStat([NotNull] LuaParser.AssignStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>functioncallStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFunctioncallStat([NotNull] LuaParser.FunctioncallStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>functioncallStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFunctioncallStat([NotNull] LuaParser.FunctioncallStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>breakStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterBreakStat([NotNull] LuaParser.BreakStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>breakStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitBreakStat([NotNull] LuaParser.BreakStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>doendStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterDoendStat([NotNull] LuaParser.DoendStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>doendStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitDoendStat([NotNull] LuaParser.DoendStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>whileStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterWhileStat([NotNull] LuaParser.WhileStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>whileStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitWhileStat([NotNull] LuaParser.WhileStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>repeatStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterRepeatStat([NotNull] LuaParser.RepeatStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>repeatStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitRepeatStat([NotNull] LuaParser.RepeatStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>ifelseStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterIfelseStat([NotNull] LuaParser.IfelseStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>ifelseStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitIfelseStat([NotNull] LuaParser.IfelseStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>forijkStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterForijkStat([NotNull] LuaParser.ForijkStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>forijkStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitForijkStat([NotNull] LuaParser.ForijkStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>forinStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterForinStat([NotNull] LuaParser.ForinStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>forinStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitForinStat([NotNull] LuaParser.ForinStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>functiondefStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFunctiondefStat([NotNull] LuaParser.FunctiondefStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>functiondefStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFunctiondefStat([NotNull] LuaParser.FunctiondefStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>localfunctiondefStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterLocalfunctiondefStat([NotNull] LuaParser.LocalfunctiondefStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>localfunctiondefStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitLocalfunctiondefStat([NotNull] LuaParser.LocalfunctiondefStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>localassignStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterLocalassignStat([NotNull] LuaParser.LocalassignStatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>localassignStat</c>
        /// labeled alternative in <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitLocalassignStat([NotNull] LuaParser.LocalassignStatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>nilfalsetruevarargExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNilfalsetruevarargExp([NotNull] LuaParser.NilfalsetruevarargExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>nilfalsetruevarargExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNilfalsetruevarargExp([NotNull] LuaParser.NilfalsetruevarargExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>numberExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNumberExp([NotNull] LuaParser.NumberExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>numberExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNumberExp([NotNull] LuaParser.NumberExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>stringExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterStringExp([NotNull] LuaParser.StringExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>stringExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitStringExp([NotNull] LuaParser.StringExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>functiondefExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFunctiondefExp([NotNull] LuaParser.FunctiondefExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>functiondefExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFunctiondefExp([NotNull] LuaParser.FunctiondefExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>prefixexpExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterPrefixexpExp([NotNull] LuaParser.PrefixexpExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>prefixexpExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitPrefixexpExp([NotNull] LuaParser.PrefixexpExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>tablectorExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterTablectorExp([NotNull] LuaParser.TablectorExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>tablectorExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitTablectorExp([NotNull] LuaParser.TablectorExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>powExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterPowExp([NotNull] LuaParser.PowExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>powExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitPowExp([NotNull] LuaParser.PowExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>unmExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterUnmExp([NotNull] LuaParser.UnmExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>unmExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitUnmExp([NotNull] LuaParser.UnmExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>muldivExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterMuldivExp([NotNull] LuaParser.MuldivExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>muldivExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitMuldivExp([NotNull] LuaParser.MuldivExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>addsubExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterAddsubExp([NotNull] LuaParser.AddsubExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>addsubExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitAddsubExp([NotNull] LuaParser.AddsubExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>concatExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterConcatExp([NotNull] LuaParser.ConcatExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>concatExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitConcatExp([NotNull] LuaParser.ConcatExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>cmpExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterCmpExp([NotNull] LuaParser.CmpExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>cmpExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitCmpExp([NotNull] LuaParser.CmpExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>andExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterAndExp([NotNull] LuaParser.AndExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>andExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitAndExp([NotNull] LuaParser.AndExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>orExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOrExp([NotNull] LuaParser.OrExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>orExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOrExp([NotNull] LuaParser.OrExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>bitwiseExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterBitwiseExp([NotNull] LuaParser.BitwiseExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>bitwiseExp</c>
        /// labeled alternative in <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitBitwiseExp([NotNull] LuaParser.BitwiseExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>normalArgs</c>
        /// labeled alternative in <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNormalArgs([NotNull] LuaParser.NormalArgsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>normalArgs</c>
        /// labeled alternative in <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNormalArgs([NotNull] LuaParser.NormalArgsContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>tablectorArgs</c>
        /// labeled alternative in <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterTablectorArgs([NotNull] LuaParser.TablectorArgsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>tablectorArgs</c>
        /// labeled alternative in <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitTablectorArgs([NotNull] LuaParser.TablectorArgsContext context) { }

        /// <summary>
        /// Enter a parse tree produced by the <c>stringArgs</c>
        /// labeled alternative in <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterStringArgs([NotNull] LuaParser.StringArgsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>stringArgs</c>
        /// labeled alternative in <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitStringArgs([NotNull] LuaParser.StringArgsContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.chunk"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterChunk([NotNull] LuaParser.ChunkContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.chunk"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitChunk([NotNull] LuaParser.ChunkContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.block"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterBlock([NotNull] LuaParser.BlockContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.block"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitBlock([NotNull] LuaParser.BlockContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterStat([NotNull] LuaParser.StatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.stat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitStat([NotNull] LuaParser.StatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterRetstat([NotNull] LuaParser.RetstatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitRetstat([NotNull] LuaParser.RetstatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFuncname([NotNull] LuaParser.FuncnameContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFuncname([NotNull] LuaParser.FuncnameContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.varlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterVarlist([NotNull] LuaParser.VarlistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.varlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitVarlist([NotNull] LuaParser.VarlistContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.namelist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNamelist([NotNull] LuaParser.NamelistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.namelist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNamelist([NotNull] LuaParser.NamelistContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.explist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterExplist([NotNull] LuaParser.ExplistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.explist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitExplist([NotNull] LuaParser.ExplistContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterExp([NotNull] LuaParser.ExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitExp([NotNull] LuaParser.ExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.nilfalsetruevararg"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNilfalsetruevararg([NotNull] LuaParser.NilfalsetruevarargContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.nilfalsetruevararg"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNilfalsetruevararg([NotNull] LuaParser.NilfalsetruevarargContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.functioncall"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFunctioncall([NotNull] LuaParser.FunctioncallContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.functioncall"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFunctioncall([NotNull] LuaParser.FunctioncallContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.varOrExp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterVarOrExp([NotNull] LuaParser.VarOrExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.varOrExp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitVarOrExp([NotNull] LuaParser.VarOrExpContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.var"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterVar([NotNull] LuaParser.VarContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.var"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitVar([NotNull] LuaParser.VarContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.varSuffix"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterVarSuffix([NotNull] LuaParser.VarSuffixContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.varSuffix"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitVarSuffix([NotNull] LuaParser.VarSuffixContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNameAndArgs([NotNull] LuaParser.NameAndArgsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNameAndArgs([NotNull] LuaParser.NameAndArgsContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterArgs([NotNull] LuaParser.ArgsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.args"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitArgs([NotNull] LuaParser.ArgsContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.funcbody"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFuncbody([NotNull] LuaParser.FuncbodyContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.funcbody"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFuncbody([NotNull] LuaParser.FuncbodyContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterParlist([NotNull] LuaParser.ParlistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitParlist([NotNull] LuaParser.ParlistContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.fieldlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFieldlist([NotNull] LuaParser.FieldlistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.fieldlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFieldlist([NotNull] LuaParser.FieldlistContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.field"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterField([NotNull] LuaParser.FieldContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.field"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitField([NotNull] LuaParser.FieldContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterFieldsep([NotNull] LuaParser.FieldsepContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitFieldsep([NotNull] LuaParser.FieldsepContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorOr"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorOr([NotNull] LuaParser.OperatorOrContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorOr"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorOr([NotNull] LuaParser.OperatorOrContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorAnd([NotNull] LuaParser.OperatorAndContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorAnd([NotNull] LuaParser.OperatorAndContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.operatorPower"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterOperatorPower([NotNull] LuaParser.OperatorPowerContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.operatorPower"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitOperatorPower([NotNull] LuaParser.OperatorPowerContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.number"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterNumber([NotNull] LuaParser.NumberContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.number"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitNumber([NotNull] LuaParser.NumberContext context) { }

        /// <summary>
        /// Enter a parse tree produced by <see cref="LuaParser.string"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void EnterString([NotNull] LuaParser.StringContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="LuaParser.string"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        [DebuggerStepThroughAttribute]
        public virtual void ExitString([NotNull] LuaParser.StringContext context) { }

        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        [DebuggerStepThroughAttribute]
        public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        [DebuggerStepThroughAttribute]
        public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        [DebuggerStepThroughAttribute]
        public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        [DebuggerStepThroughAttribute]
        public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
    }
} // namespace zlua.AntlrGen
