//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-beta001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\91018\Documents\GitHub\zlua\zlua\Lua.g4 by ANTLR 4.6.5-beta001

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace zlua {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILuaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-beta001")]
[System.CLSCompliant(false)]
public partial class LuaBaseListener : ILuaListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>empty_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmpty_stat([NotNull] LuaParser.Empty_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>empty_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmpty_stat([NotNull] LuaParser.Empty_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>assign_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_stat([NotNull] LuaParser.Assign_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>assign_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_stat([NotNull] LuaParser.Assign_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>func_call_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call_stat([NotNull] LuaParser.Func_call_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>func_call_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call_stat([NotNull] LuaParser.Func_call_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>break_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak_stat([NotNull] LuaParser.Break_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>break_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak_stat([NotNull] LuaParser.Break_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>do_end_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDo_end_stat([NotNull] LuaParser.Do_end_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>do_end_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDo_end_stat([NotNull] LuaParser.Do_end_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>while_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_stat([NotNull] LuaParser.While_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>while_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_stat([NotNull] LuaParser.While_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>if_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stat([NotNull] LuaParser.If_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>if_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stat([NotNull] LuaParser.If_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>func_def_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_def_stat([NotNull] LuaParser.Func_def_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>func_def_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_def_stat([NotNull] LuaParser.Func_def_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>global_func_def_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobal_func_def_stat([NotNull] LuaParser.Global_func_def_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>global_func_def_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobal_func_def_stat([NotNull] LuaParser.Global_func_def_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>global_var_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobal_var_stat([NotNull] LuaParser.Global_var_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>global_var_stat</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobal_var_stat([NotNull] LuaParser.Global_var_statContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>nil_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNil_exp([NotNull] LuaParser.Nil_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nil_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNil_exp([NotNull] LuaParser.Nil_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>false_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalse_exp([NotNull] LuaParser.False_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>false_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalse_exp([NotNull] LuaParser.False_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>true_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrue_exp([NotNull] LuaParser.True_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>true_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrue_exp([NotNull] LuaParser.True_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>num_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_exp([NotNull] LuaParser.Num_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_exp([NotNull] LuaParser.Num_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>string_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_exp([NotNull] LuaParser.String_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>string_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_exp([NotNull] LuaParser.String_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>func_def_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_def_exp([NotNull] LuaParser.Func_def_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>func_def_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_def_exp([NotNull] LuaParser.Func_def_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>prefix_exp_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefix_exp_exp([NotNull] LuaParser.Prefix_exp_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>prefix_exp_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefix_exp_exp([NotNull] LuaParser.Prefix_exp_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>table_ctor_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_ctor_exp([NotNull] LuaParser.Table_ctor_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>table_ctor_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_ctor_exp([NotNull] LuaParser.Table_ctor_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_unary_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_unary_exp([NotNull] LuaParser.Op_unary_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_unary_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_unary_exp([NotNull] LuaParser.Op_unary_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_mul_div_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_mul_div_exp([NotNull] LuaParser.Op_mul_div_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_mul_div_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_mul_div_exp([NotNull] LuaParser.Op_mul_div_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_add_sub_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_add_sub_exp([NotNull] LuaParser.Op_add_sub_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_add_sub_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_add_sub_exp([NotNull] LuaParser.Op_add_sub_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_concat_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_concat_exp([NotNull] LuaParser.Op_concat_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_concat_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_concat_exp([NotNull] LuaParser.Op_concat_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_caompare_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_caompare_exp([NotNull] LuaParser.Op_caompare_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_caompare_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_caompare_exp([NotNull] LuaParser.Op_caompare_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_and_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_and_exp([NotNull] LuaParser.Op_and_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_and_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_and_exp([NotNull] LuaParser.Op_and_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>op_or_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_or_exp([NotNull] LuaParser.Op_or_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>op_or_exp</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_or_exp([NotNull] LuaParser.Op_or_expContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChunk([NotNull] LuaParser.ChunkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChunk([NotNull] LuaParser.ChunkContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] LuaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] LuaParser.BlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] LuaParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] LuaParser.StatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstat([NotNull] LuaParser.RetstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstat([NotNull] LuaParser.RetstatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] LuaParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] LuaParser.FuncnameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] LuaParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] LuaParser.VarlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamelist([NotNull] LuaParser.NamelistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamelist([NotNull] LuaParser.NamelistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.explist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplist([NotNull] LuaParser.ExplistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.explist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplist([NotNull] LuaParser.ExplistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] LuaParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] LuaParser.ExpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctioncall([NotNull] LuaParser.FunctioncallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctioncall([NotNull] LuaParser.FunctioncallContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrExp([NotNull] LuaParser.VarOrExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrExp([NotNull] LuaParser.VarOrExpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] LuaParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] LuaParser.VarContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarSuffix([NotNull] LuaParser.VarSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarSuffix([NotNull] LuaParser.VarSuffixContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameAndArgs([NotNull] LuaParser.NameAndArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameAndArgs([NotNull] LuaParser.NameAndArgsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] LuaParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] LuaParser.ArgsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncbody([NotNull] LuaParser.FuncbodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncbody([NotNull] LuaParser.FuncbodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParlist([NotNull] LuaParser.ParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParlist([NotNull] LuaParser.ParlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldlist([NotNull] LuaParser.FieldlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldlist([NotNull] LuaParser.FieldlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] LuaParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] LuaParser.FieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsep([NotNull] LuaParser.FieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsep([NotNull] LuaParser.FieldsepContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOr([NotNull] LuaParser.OperatorOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOr([NotNull] LuaParser.OperatorOrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAnd([NotNull] LuaParser.OperatorAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAnd([NotNull] LuaParser.OperatorAndContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorPower([NotNull] LuaParser.OperatorPowerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorPower([NotNull] LuaParser.OperatorPowerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] LuaParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] LuaParser.NumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] LuaParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] LuaParser.StringContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace zlua
