//========================================================================
// This conversion was produced by the Free Edition of
// C++ to C# Converter courtesy of Tangible Software Solutions.
// Order the Premium Edition at https://www.tangiblesoftwaresolutions.com
//========================================================================

internal static class DefineConstants
{
	public const string LUA_PATH = "LUA_PATH";
	public const string LUA_CPATH = "LUA_CPATH";
	public const string LUA_INIT = "LUA_INIT";
	public const string LUA_LDIR = "!\\lua\\";
	public const string LUA_CDIR = "!\\";
	public const string LUA_ROOT = "/usr/local/";
//C++ TO C# CONVERTER TODO TASK: The following #define constant was defined in different ways:
	public const string LUA_DIRSEP = "\\";
	public const string LUA_DIRSEP = "/";
	public const string LUA_PATHSEP = ";";
	public const string LUA_PATH_MARK = "?";
	public const string LUA_EXECDIR = "!";
	public const string LUA_IGMARK = "-";
	public const int LUA_IDSIZE = 60;
	public const string LUA_PROMPT = "> ";
	public const string LUA_PROMPT2 = ">> ";
	public const string LUA_PROGNAME = "lua";
	public const int LUA_MAXINPUT = 512;
	public const int LUAI_GCPAUSE = 200; // 200% (wait memory to double before next GC)
	public const int LUAI_GCMUL = 200; // GC runs 'twice the speed' of memory allocation
	public const int LUA_COMPAT_LSTR = 1;
//C++ TO C# CONVERTER TODO TASK: The following #define constant was defined in different ways:
	public const int LUAI_BITSINT = 16;
	public const int LUAI_BITSINT = 32;
	public const int LUAI_MAXCALLS = 20000;
	public const int LUAI_MAXCSTACK = 8000;
	public const int LUAI_MAXCCALLS = 200;
	public const int LUAI_MAXVARS = 200;
	public const int LUAI_MAXUPVALUES = 60;
	public const string LUA_NUMBER_SCAN = "%lf";
	public const string LUA_NUMBER_FMT = "%.14g";
	public const int LUAI_MAXNUMBER2STR = 32; // 16 digits, sign, point, and \0
	public const int LUA_MAXCAPTURES = 32;
	public const int LUA_TMPNAMBUFSIZE = 32;
	public const int LUAI_EXTRASPACE = 0;
//C++ TO C# CONVERTER TODO TASK: The following #define constant was defined in different ways:
	public const string LUA_INTFRMLEN = "ll";
	public const string LUA_INTFRMLEN = "l";
	public const string LUA_VERSION = "Lua 5.1";
	public const string LUA_RELEASE = "Lua 5.1.4";
	public const int LUA_VERSION_NUM = 501;
	public const string LUA_COPYRIGHT = "Copyright (C) 1994-2008 Lua.org, PUC-Rio";
	public const string LUA_AUTHORS = "R. Ierusalimschy, L. H. de Figueiredo & W. Celes";
	public const string LUA_SIGNATURE = "\x001BLua";
	public const int LUA_MULTRET = -1;
	public const int LUA_REGISTRYINDEX = -10000;
	public const int LUA_ENVIRONINDEX = -10001;
	public const int LUA_GLOBALSINDEX = -10002;
	public const int LUA_YIELD = 1;
	public const int LUA_ERRRUN = 2;
	public const int LUA_ERRSYNTAX = 3;
	public const int LUA_ERRMEM = 4;
	public const int LUA_ERRERR = 5;
	public const int LUA_TNONE = -1;
	public const int LUA_TNIL = 0;
	public const int LUA_TBOOLEAN = 1;
	public const int LUA_TLIGHTUSERDATA = 2;
	public const int LUA_TNUMBER = 3;
	public const int LUA_TSTRING = 4;
	public const int LUA_TTABLE = 5;
	public const int LUA_TFUNCTION = 6;
	public const int LUA_TUSERDATA = 7;
	public const int LUA_TTHREAD = 8;
	public const int LUA_MINSTACK = 20;
	public const int LUA_GCSTOP = 0;
	public const int LUA_GCRESTART = 1;
	public const int LUA_GCCOLLECT = 2;
	public const int LUA_GCCOUNT = 3;
	public const int LUA_GCCOUNTB = 4;
	public const int LUA_GCSTEP = 5;
	public const int LUA_GCSETPAUSE = 6;
	public const int LUA_GCSETSTEPMUL = 7;
	public const int LUA_HOOKCALL = 0;
	public const int LUA_HOOKRET = 1;
	public const int LUA_HOOKLINE = 2;
	public const int LUA_HOOKCOUNT = 3;
	public const int LUA_HOOKTAILRET = 4;
	public const int MAXSTACK = 250;
	public const int MINSTRTABSIZE = 32;
	public const int LUA_MINBUFFER = 32;
	public const int VARARG_HASARG = 1;
	public const int VARARG_ISVARARG = 2;
	public const int VARARG_NEEDSARG = 4;
	public const string MEMERRMSG = "not enough memory";
	public const int EOZ = -1; // end of stream
	public const int EXTRA_STACK = 5;
	public const int BASIC_CI_SIZE = 8;
	public const int PCRLUA = 0; // initiated a call to a Lua function
	public const int PCRC = 1; // did a call to a C function
	public const int PCRYIELD = 2; // C funtion yielded
	public const int GCSpause = 0;
	public const int GCSpropagate = 1;
	public const int GCSsweepstring = 2;
	public const int GCSsweep = 3;
	public const int GCSfinalize = 4;
	public const int WHITE0BIT = 0;
	public const int WHITE1BIT = 1;
	public const int BLACKBIT = 2;
	public const int FINALIZEDBIT = 3;
	public const int KEYWEAKBIT = 3;
	public const int VALUEWEAKBIT = 4;
	public const int FIXEDBIT = 5;
	public const int SFIXEDBIT = 6;
	public const int LUAC_VERSION = 0x51;
	public const int LUAC_FORMAT = 0;
	public const int LUAC_HEADERSIZE = 12;
	public const int LUA_NOREF = -2;
	public const int LUA_REFNIL = -1;
	public const int FREELIST_REF = 0; // free list of references
	public const string LUA_FILEHANDLE = "FILE*";
	public const string LUA_COLIBNAME = "coroutine";
	public const string LUA_TABLIBNAME = "table";
	public const string LUA_IOLIBNAME = "io";
	public const string LUA_OSLIBNAME = "os";
	public const string LUA_STRLIBNAME = "string";
	public const string LUA_MATHLIBNAME = "math";
	public const string LUA_DBLIBNAME = "debug";
	public const string LUA_LOADLIBNAME = "package";
	public const int CO_RUN = 0; // running
	public const int CO_SUS = 1; // suspended
	public const int CO_NOR = 2; // 'normal' (it resumed another coroutine)
	public const int CO_DEAD = 3;
	public const int FIRST_RESERVED = 257;
	public const int SIZE_C = 9;
	public const int SIZE_B = 9;
	public const int SIZE_A = 8;
	public const int SIZE_OP = 6;
	public const int POS_OP = 0;
	public const int LFIELDS_PER_FLUSH = 50;
	public const int NO_JUMP = -1;
	public const int LEVELS1 = 12; // size of the first part of the stack
	public const int LEVELS2 = 10; // size of the second part of the stack
	public const uint GCSTEPSIZE = 1024;
	public const int GCSWEEPMAX = 40;
	public const int GCSWEEPCOST = 10;
	public const int GCFINALIZECOST = 100;
	public const int IO_INPUT = 1;
	public const int IO_OUTPUT = 2;
	public const int MAXSRC = 80;
	public const double PI = (3.14159265358979323846);
	public const int MINSIZEARRAY = 4;
	public const string LUA_POF = "luaopen_";
	public const string LUA_OFSEP = "_";
	public const string LIBPREFIX = "LOADLIB: ";
//C++ TO C# CONVERTER TODO TASK: The following #define constant was defined in different ways:
	public const string LIB_FAIL = "open";
	public const string LIB_FAIL = "absent";
	public const int ERRLIB = 1;
	public const int ERRFUNC = 2;
	public const string DLMSG = "dynamic libraries not enabled; check your Lua installation";
	public const string AUXMARK = "\x0001";
	public const int UNARY_PRIORITY = 8; // priority for unary operators
	public const int CAP_UNFINISHED = -1;
	public const int CAP_POSITION = -2;
	public const char L_ESC = '%';
	public const string SPECIALS = "^$*+?.([%-";
	public const int MAX_ITEM = 512;
	public const string FLAGS = "-+ #0";
	public const int MAXBITS = 26;
	public const string PROGNAME = "luac"; // default program name
	public const int MAXTAGLOOP = 100;
}